USE MagazinMercerie
GO

CREATE OR ALTER PROCEDURE deadlock_T1_csharp AS
BEGIN
	BEGIN TRANSACTION
	UPDATE FirBumbac SET Culoare='Negru' WHERE Fid=4
	WAITFOR DELAY '00:00:08'
	UPDATE Angajat SET Nume='Mariuta' WHERE AngajatId=4
	COMMIT TRANSACTION
END

CREATE OR ALTER PROCEDURE deadlock_T2_csharp AS
BEGIN
	SET DEADLOCK_PRIORITY HIGH
	BEGIN TRANSACTION
	UPDATE Angajat SET Nume='Anamaria' WHERE AngajatId=4
	WAITFOR DELAY '00:00:08'
	UPDATE FirBumbac SET Culoare='Alb' WHERE Fid=4
	COMMIT TRANSACTION
END