USE MagazinMercerie;
GO


CREATE OR ALTER PROCEDURE dirty_reads_T1 AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
		UPDATE FirBumbac SET
		Culoare='Roz' WHERE Fid=2
		WAITFOR DELAY '00:00:08'
		ROLLBACK TRANSACTION
		PRINT 'Transaction T1 rollback successful'
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		PRINT 'Transaction T1 failed'
	END CATCH
END

CREATE OR ALTER PROCEDURE dirty_reads_T2 AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL READ COMMITTED
		BEGIN TRANSACTION
		SELECT * FROM FirBumbac
		WAITFOR DELAY '00:00:12'
		SELECT * FROM FirBumbac
		COMMIT TRANSACTION
		PRINT 'Transaction T2 commit successful'
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		PRINT 'Transaction T2 failed'
	END CATCH
END

EXEC dirty_reads_T1
EXEC dirty_reads_T2