USE MagazinMercerie;
GO

SELECT * FROM FirBumbac

CREATE OR ALTER PROCEDURE phantom_reads_T1 AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
		WAITFOR DELAY '00:00:08'
		INSERT INTO FirBumbac(Fid, Culoare, Lungime, Grosime, Gid) VALUES
		(4, 'Roz', 130, 5, 1);
		COMMIT TRANSACTION
		PRINT 'Transaction T1 commit successful'
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		PRINT 'Transaction T1 failed'
	END CATCH
END

CREATE OR ALTER PROCEDURE phantom_reads_T2 AS
BEGIN
	BEGIN TRY
		SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
		BEGIN TRANSACTION
		SELECT * FROM FirBumbac
		WAITFOR DELAY '00:00:12'
		SELECT * FROM FirBumbac
		COMMIT TRANSACTION
		PRINT 'Transaction T2 commit successful'
	END TRY
	BEGIN CATCH
		ROLLBACK TRANSACTION
		PRINT 'Transaction T2 failed'
	END CATCH
END

DELETE FROM FirBumbac WHERE Fid=4;
SELECT * FROM FirBumbac;

EXEC phantom_reads_T1
EXEC phantom_reads_T2
